apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: myapp
   namespace: argocd
spec:
   project: default
   destination:
      namespace: default
      server: https://kubernetes.default.svc
   source:
      repoURL: https://github.com/myrepo/myapp.git
      targetRevision: main
      path: k8s
   syncPolicy:
      automated:
         prune: true
         selfHeal: true