name: CI/CD Pipeline
on:
   push:
   branches:
      - main
jobs:
   build:
      runs-on: ubuntu-latest
   steps:
      - name: Checkout Code
         uses: actions/checkout@v3
      - name: Set up Docker
         uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
         run: |
            docker build -t myapp:latest .
      - name: Push to Docker Hub
         run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker tag myapp:latest myrepo/myapp:latest
            docker push myrepo/myapp:latest
